# Palo Alto Researcher
205.210.31.0/24
198.235.24.0/24
162.216.150.0/24
162.216.149.0/24
147.185.132.0/22
35.203.210.0/24
# ShadowServer Researcher
216.218.128.0/17
184.104.0.0/15
64.62.128.0/18
64.62.197.0/24
64.62.156.0/24
65.49.0.0/17
# Censys Researcher
206.168.34.0/24
199.45.155.0/24
167.94.146.0/24
167.94.145.0/24
167.94.138.0/24
162.142.125.0/24
# Cypex.ai Researcher
3.149.59.26/32
3.143.33.63/32
3.137.73.221/32
3.134.148.59/32
3.132.23.201/32
3.131.215.38/32
3.130.96.91/32
# Shodan
66.240.192.0/18
71.6.128.0/17
82.221.96.0/19
