"205.210.31.0/24" : Palo Alto Researcher
"198.235.24.0/24" : Palo Alto Researcher
"147.185.132.0/22" : Palo Alto Researcher
"216.218.128.0/17" : Shadow Server Researcher
"184.104.0.0/15" : Shadow Server Researcher
"64.62.128.0/18" : Shadow Server Researcher
"64.62.197.0/24" : Shadow Server Researcher
"64.62.156.0/24" : Shadow Server Researcher
"65.49.0.0/17" : Shadow Server Researcher
"206.168.34.0/24" : Censys Researcher
"199.45.155.0/24" : Censys Researcher
"167.94.146.0/24" : Censys Researcher
"167.94.145.0/24" : Censys Researcher
"167.94.138.0/24" : Censys Researcher
"162.142.125.0/24" : Censys Researcher

