"216.218.128.0/17": "Shadow Server Researcher"
"184.104.0.0/15": "Shadow Server Researcher"
"64.62.128.0/18": "Shadow Server Researcher"
"64.62.197.0/24": "Shadow Server Researcher"
"64.62.156.0/24": "Shadow Server Researcher"
"65.49.0.0/17": "Shadow Server Researcher"
"206.168.34.0/24": "Censys Researcher"
"199.45.155.0/24": "Censys Researcher"
"167.94.146.0/24": "Censys Researcher"
"167.94.145.0/24": "Censys Researcher"
"167.94.138.0/24": "Censys Researcher"
"162.142.125.0/24": "Censys Researcher"
"3.149.59.26/32": "Cypex.ai Researcher"
"3.143.33.63/32": "Cypex.ai Researcher"
"3.137.73.221/32": "Cypex.ai Researcher"
"3.134.148.59/32": "Cypex.ai Researcher"
"3.132.23.201/32": "Cypex.ai Researcher"
"3.131.215.38/32": "Cypex.ai Researcher"
"3.130.96.91/32": "Cypex.ai Researcher"
